CXX = g++ 
CXXFLAGS = -std=c++20

defining-interfaces: defining-interfaces.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

clean-defining-interfaces:
	rm defining-interfaces

construction-injection: construction-injection.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

clean-construction-injection:
	rm construction-injection

property-injection: property-injection.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

clean-property-injection:
	rm property-injection

bank: bank.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

clean-bank:
	rm bank


