CXX = g++ 
CXXFLAGS = -std=c++20

tracer: tracer.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

groucho: groucho.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

simplestring: simplestring.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

copyconstructors: copyconstructors.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

timerclass: timerclass.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

