CXX = g++ 
CXXFLAGS = -std=c++20

forward-linked-lists: forward-linked-lists.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

reseat-reference: reseat-reference.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

doubly-linked-lists: doubly-linked-lists.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

